# Generated by Django 5.2.6 on 2025-09-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="boolean_field",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="date_field",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="float_field",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="integer_field",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="test_field",
            field=models.TextField(blank=True, null=True),
        ),
    ]
