# Generated by Django 5.2.6 on 2025-09-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0002_alter_value_boolean_field_alter_value_date_field_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="value",
            old_name="test_field",
            new_name="text_field",
        ),
    ]
