# Generated by Django 5.2.6 on 2025-09-17 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0003_rename_test_field_value_text_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="eav.attribute",
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="eav.entity",
            ),
        ),
    ]
